---
title: "intermediate-elective"
date: "2026-05-10"
author: "Linda Herrera"
format: pdf
---

## Set up

### Packages

```{r}
#| label: packages
#| message: false
#| warning: false

# general use and cleaning
library(tidyverse)
library(here)
library(janitor)
library(snakecase)

# wrapping axis labels
library(scales)

# reading in .xlsx files
library(readxl)

# visualizations and coloring
library(RColorBrewer)
```

### Data

```{r}
#| label: data
#| message: false
#| warning: false

# taxonomic information
taxon_list <- read_csv(here("data", "taxon_list.csv")) 

# aquatic invertebrates
aq_ins <- read_xlsx(here("data", "Aquatic Sampling Data-2026-03-10.xlsx"),
                    sheet = "Aquatic Insects") 

# site information
sites <- read_xlsx(here("data", "Aquatic Sampling Data-2026-03-10.xlsx"),
                   sheet = "sites")

# water quality information
water_quality <- read_xlsx(here("data", "Aquatic Sampling Data-2026-03-10.xlsx"),
                           sheet = "Water Quality",
                           na = c("", "n/a", "N/A", "over", "173+")) 

# vegetation information 
veg <- read_csv(here("data", "veg.csv"))

# vegetation meta data information
metadata <- read_csv(here("data", "vp_veg_metadata.csv"))
```

## Problems 

### 1. Explain your inspiration


## 2. Plan your figure


## 3. Code your figure


## 4. Describe your process



















